/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/s/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["renderSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCustomerApiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/password/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["customerPasswordLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestCustomerOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCustomerOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/register/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestCustomerRegistrationOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/register/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCustomerRegistrationOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCustomerSession"];
        put?: never;
        post: operations["updateCustomerProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/auth/password/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setCustomerPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomerSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer/v1/brand-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicBrandConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminApiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/password/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["staffPasswordLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyStaffOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStaffSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminSubscriptions"];
        put?: never;
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        get: operations["getAdminSubscription"];
        put?: never;
        post?: never;
        /** @description Soft-revokes the subscription and every active subscription token; no business record is deleted. */
        delete: operations["revokeAdminSubscription"];
        options?: never;
        head?: never;
        patch: operations["updateAdminSubscription"];
        trace?: never;
    };
    "/admin/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/customers/{customerId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminCustomerStatus"];
        trace?: never;
    };
    "/admin/v1/brand-memberships/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminBrandMembership"];
        trace?: never;
    };
    "/admin/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/plans/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setPlanPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/subscriptions/{subscriptionId}/tokens/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateSubscriptionToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWebhookApiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInternalApiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/endpoints/probe-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEndpointProbeTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/endpoints/{endpointId}/probe-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordEndpointProbeResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/subscriptions/{subscriptionId}/profile-bindings/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upsertEncryptedProfileBinding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/provisioning/run-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Claims and processes one pending provisioning job (PROVISION or REVOKE), if any. Intended to be called repeatedly by an external worker/cron; retries and backoff are tracked in provisioning_jobs and do not need external scheduling logic. */
        post: operations["runNextProvisioningJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInfrastructureSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listControlPlaneSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInfrastructureEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInfrastructureIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/endpoint-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEndpointGroups"];
        put?: never;
        post: operations["createEndpointGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/endpoint-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEndpointGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateEndpointGroup"];
        trace?: never;
    };
    "/admin/v1/infrastructure/endpoint-groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replaceEndpointGroupMembers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/infrastructure/endpoint-groups/{id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replaceEndpointGroupPlans"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EmailOnly: {
            /** Format: email */
            email: string;
        };
        PasswordLogin: components["schemas"]["EmailOnly"] & {
            /** Format: password */
            password: string;
        };
        CustomerPasswordLogin: components["schemas"]["PasswordLogin"] & {
            brandCode: string;
        };
        CustomerOtpRequest: components["schemas"]["EmailOnly"] & {
            brandCode: string;
        };
        OtpVerify: components["schemas"]["EmailOnly"] & {
            code: string;
        };
        CustomerOtpVerify: components["schemas"]["OtpVerify"] & {
            brandCode: string;
        };
        SessionToken: {
            accessToken: string;
            /** @constant */
            tokenType: "Bearer";
            /** @enum {string} */
            audience: "customer" | "staff";
            /** Format: date-time */
            expiresAt: string;
        };
        AuthPrincipal: {
            /** @enum {string} */
            audience: "customer" | "staff";
            /** Format: uuid */
            identityId: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: email */
            email: string;
            permissions: string[];
        };
        StaffProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            roles: string[];
            permissions: string[];
        };
        CustomerProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            memberships: {
                brandCode: string;
                brandName: string;
                status: string;
            }[];
        };
        UpdateCustomerProfile: {
            displayName: string;
        };
        PublicBrandConfig: {
            code: string;
            name: string;
        } & {
            [key: string]: unknown;
        };
        CustomerPlan: {
            name: string;
            /** @enum {string} */
            billingModel: "DEVICE_PLAN" | "ACCOUNT_PLAN" | "FAMILY_PLAN";
            deviceLimit: number;
        };
        SubscriptionSummary: {
            /** Format: uuid */
            id: string;
            brandCode: string;
            planCode?: string | null;
            /** @enum {string} */
            status: "PENDING" | "TRIAL" | "ACTIVE" | "PAST_DUE" | "EXPIRED" | "SUSPENDED" | "REVOKED";
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Monotonic bigint serialized as a string */
            revision: string;
            /** @description Non-secret display prefix; never the subscription token or its hash */
            tokenPrefix?: string | null;
            /**
             * Format: uri
             * @description Secret URL returned only to the authenticated customer and authorized staff.
             */
            subscriptionUrl?: string | null;
            plan?: components["schemas"]["CustomerPlan"] | null;
            /** Format: email */
            customerEmail?: string;
        };
        SubscriptionDetail: components["schemas"]["SubscriptionSummary"] & {
            /** Format: uuid */
            brandMembershipId?: string;
            /** Format: uuid */
            planId?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        SubscriptionPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["SubscriptionSummary"][];
        };
        UpdateSubscription: {
            /** Format: uuid */
            planId?: string;
            /** @enum {string} */
            status?: "PENDING" | "TRIAL" | "ACTIVE" | "PAST_DUE" | "EXPIRED" | "SUSPENDED" | "REVOKED";
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            reason: string;
        };
        ReasonInput: {
            reason: string;
        };
        PageMetadata: {
            page: number;
            pageSize: number;
            total: number;
        };
        BrandMembershipSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brandId: string;
            brandCode: string;
            brandName: string;
            status: string;
        };
        UpdateMembership: {
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED";
        };
        CustomerSummary: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            memberships: components["schemas"]["BrandMembershipSummary"][];
        };
        CustomerSubscriptionSummary: {
            /** Format: uuid */
            id: string;
            brandCode: string;
            planCode: string | null;
            planName: string | null;
            status: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            expiresAt: string;
            endpointGroups: {
                /** Format: uuid */
                id?: string;
                code?: string;
                name?: string;
            }[];
        };
        CustomerDetail: components["schemas"]["CustomerSummary"] & {
            subscriptions: components["schemas"]["CustomerSubscriptionSummary"][];
        };
        CustomerPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["CustomerSummary"][];
        };
        PlanSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brandId: string;
            brandCode: string;
            code: string;
            name: string;
            /** @enum {string} */
            billingModel: "DEVICE_PLAN" | "ACCOUNT_PLAN" | "FAMILY_PLAN";
            deviceLimit: number;
            status: string;
            price?: {
                amount?: number;
                currency?: string;
            } | null;
        };
        PlanPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["PlanSummary"][];
        };
        AuditEventSummary: {
            /** Format: uuid */
            id: string;
            actorType: string;
            /** Format: uuid */
            actorId?: string | null;
            action: string;
            resourceType: string;
            resourceId?: string | null;
            requestId?: string | null;
            reason?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        AuditEventPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["AuditEventSummary"][];
        };
        CreateSubscription: {
            /** Format: uuid */
            brandMembershipId: string;
            /** Format: uuid */
            planId?: string;
            /** @enum {string} */
            status: "PENDING" | "TRIAL" | "ACTIVE";
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        RotateSubscriptionToken: {
            /** Format: date-time */
            expiresAt?: string;
        };
        IssuedSubscriptionToken: {
            /** @description Plaintext token returned once; only its hash and authenticated ciphertext are persisted. */
            token: string;
            tokenPrefix: string;
            /** Format: uri */
            subscriptionUrl: string;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        EndpointProbeTarget: {
            /** Format: uuid */
            id: string;
            name: string;
            countryCode: string;
            protocol: string;
            transport?: string | null;
            healthStatus: string;
        };
        EndpointProbeResultInput: {
            probeId: string;
            regionCode: string;
            networkType: string;
            success: boolean;
            latencyMs?: number;
            errorCode?: string;
            checks: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            observedAt: string;
        };
        UpsertProfileBinding: {
            /** @enum {string} */
            providerType: "REMNAWAVE" | "THREE_X_UI" | "HYSTERIA2" | "WIREGUARD";
            providerBindingRef: string;
            /** @description Plaintext exists only in the authenticated request and process memory. */
            profileUri: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        ProvisioningRunResult: {
            /** @description Whether a pending job was found and attempted */
            processed: boolean;
            /** Format: uuid */
            jobId?: string;
            /** @enum {string} */
            status?: "SUCCEEDED" | "PENDING_RETRY" | "FAILED";
        };
        InfrastructureSummary: {
            sources: number;
            endpoints: number;
            healthy: number;
            unhealthy: number;
            openIncidents: number;
        };
        ControlPlaneSourceSummary: {
            /** Format: uuid */
            id: string;
            code: string;
            providerType: string;
            status: string;
            capabilities: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            lastInventoryAt?: string | null;
            lastInventoryStatus?: string | null;
            lastInventoryError?: string | null;
            endpointCount: number;
            unhealthyCount: number;
        };
        InfrastructureEndpointSummary: {
            /** Format: uuid */
            id: string;
            sourceCode: string;
            name: string;
            countryCode: string;
            city?: string | null;
            protocol: string;
            transport?: string | null;
            healthStatus: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: date-time */
            lastProbeAt?: string | null;
        };
        InfrastructureEndpointPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["InfrastructureEndpointSummary"][];
        };
        InfrastructureIncidentSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            endpointId?: string | null;
            endpointName?: string | null;
            /** @enum {string} */
            severity: "INFO" | "WARNING" | "CRITICAL";
            /** @enum {string} */
            status: "OPEN" | "ACKNOWLEDGED" | "RESOLVED";
            kind: string;
            summary: string;
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        InfrastructureIncidentPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["InfrastructureIncidentSummary"][];
        };
        EndpointGroupSummary: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            routeClass: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EndpointGroupListItem: components["schemas"]["EndpointGroupSummary"] & {
            memberCount: number;
            planCount: number;
        };
        EndpointGroupPage: components["schemas"]["PageMetadata"] & {
            items: components["schemas"]["EndpointGroupListItem"][];
        };
        EndpointGroupMemberEndpoint: {
            /** Format: uuid */
            id: string;
            name: string;
            countryCode: string;
            protocol: string;
            healthStatus: string;
        };
        EndpointGroupPlanRef: {
            /** Format: uuid */
            id: string;
            brandCode: string;
            code: string;
            name: string;
        };
        EndpointGroupDetail: components["schemas"]["EndpointGroupSummary"] & {
            endpoints: components["schemas"]["EndpointGroupMemberEndpoint"][];
            plans: components["schemas"]["EndpointGroupPlanRef"][];
        };
        CreateEndpointGroup: {
            code: string;
            name: string;
            routeClass?: string;
        };
        UpdateEndpointGroup: {
            name?: string;
            routeClass?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
        };
        ReplaceEndpointGroupMembers: {
            endpointIds: string[];
        };
        EndpointGroupMembership: {
            /** Format: uuid */
            id: string;
            endpointIds: string[];
        };
        ReplaceEndpointGroupPlans: {
            planIds: string[];
        };
        EndpointGroupPlanAccess: {
            /** Format: uuid */
            id: string;
            planIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    renderSubscription: {
        parameters: {
            query?: {
                format?: "plain" | "base64" | "sing-box" | "xray" | "mihomo";
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health-filtered non-cacheable subscription body. `sing-box` and `xray` return a JSON document `{ "outbounds": [...] }`; `mihomo` returns a YAML document `{ proxies: [...] }` - one entry per eligible endpoint, in each format's own schema. Endpoints using a transport the selected format does not support (XHTTP for all three structured formats currently) or a protocol the renderer does not yet cover are silently omitted rather than emitted as a broken entry. When `format` is omitted and the request's User-Agent looks like an ordinary browser (not a recognized VPN client), an HTML status page is returned instead of a subscription body, showing status/expiry/server count, a copyable subscription link, and each eligible server's own direct decrypted link - mirroring how panels like 3x-ui present their own subscription links to a browser versus a client app. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "application/json": Record<string, never>;
                    "application/yaml": string;
                    "text/html": string;
                };
            };
            /** @description Unsupported format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token or subscription unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency readiness status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCustomerApiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer API contour status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customerPasswordLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPasswordLogin"];
            };
        };
        responses: {
            /** @description Customer session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionToken"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestCustomerOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerOtpRequest"];
            };
        };
        responses: {
            /** @description Request accepted without account disclosure */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyCustomerOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerOtpVerify"];
            };
        };
        responses: {
            /** @description Customer session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionToken"];
                };
            };
            /** @description Invalid or expired code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestCustomerRegistrationOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerOtpRequest"];
            };
        };
        responses: {
            /** @description Registration request accepted without account disclosure */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyCustomerRegistrationOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerOtpVerify"];
            };
        };
        responses: {
            /** @description Customer account, brand membership and session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionToken"];
                };
            };
        };
    };
    getCustomerSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current customer principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Invalid customer session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCustomerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerProfile"];
            };
        };
        responses: {
            /** @description Updated customer profile */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
        };
    };
    logoutCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setCustomerPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password updated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid customer session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCustomerSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriptions belonging to the authenticated customer across brands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSummary"][];
                };
            };
            /** @description Invalid customer session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicBrandConfig: {
        parameters: {
            query?: {
                brandCode?: string;
                hostname?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public white-label brand configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBrandConfig"];
                };
            };
            /** @description brandCode or hostname is required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Brand not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminApiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin API contour status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    staffPasswordLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLogin"];
            };
        };
        responses: {
            /** @description Password accepted; email OTP is required */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyStaffOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            /** @description MFA-verified staff session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionToken"];
                };
            };
            /** @description Invalid or expired code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStaffSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current staff principal and permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffProfile"];
                };
            };
            /** @description Invalid staff session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAdminSubscriptions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                brandCode?: string;
                customerEmail?: string;
                status?: string;
                sortBy?: "createdAt" | "expiresAt" | "status";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription administration list; requires subscriptions.read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPage"];
                };
            };
            /** @description Missing subscriptions.read permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscription"];
            };
        };
        responses: {
            /** @description Subscription created; requires subscriptions.write */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSummary"];
                };
            };
            /** @description Invalid period */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing subscriptions.write permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAdminSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDetail"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeAdminSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description Subscription revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAdminSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscription"];
            };
        };
        responses: {
            /** @description Subscription updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid period */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAdminCustomers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
                brandCode?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated customers and brand memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
        };
    };
    getAdminCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer detail with brand memberships and subscriptions across all brands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAdminCustomerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembership"];
            };
        };
        responses: {
            /** @description Customer status updated and audited. Unlike PATCH /admin/v1/brand-memberships/ {membershipId}, which blocks one specific brand, this blocks (or restores) the customer everywhere at once - existing sessions in every brand are rejected on their next request, not just future logins. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAdminBrandMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembership"];
            };
        };
        responses: {
            /** @description Membership status updated and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Membership not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAdminPlans: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                brandCode?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated selectable plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanPage"];
                };
            };
        };
    };
    setPlanPrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: number;
                    currency: string;
                };
            };
        };
        responses: {
            /** @description New price version recorded, effective immediately. Subscriptions created before this call keep referencing the price that was current when they were issued - this only ever adds a new row, it never rewrites history. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        planId?: string;
                        amount?: number;
                        currency?: string;
                    };
                };
            };
            /** @description Plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAdminAuditEvents: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                action?: string;
                actorType?: string;
                resourceType?: string;
                actorId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated audit metadata; sensitive before/after payloads are excluded from this list contract */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
        };
    };
    rotateSubscriptionToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RotateSubscriptionToken"];
            };
        };
        responses: {
            /** @description New plaintext token, returned exactly once; previous active token is revoked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedSubscriptionToken"];
                };
            };
            /** @description Missing subscriptions.write permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWebhookApiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook API contour status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInternalApiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Internal API contour status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEndpointProbeTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Non-secret endpoint targets for regional agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointProbeTarget"][];
                };
            };
            /** @description Invalid internal credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordEndpointProbeResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndpointProbeResultInput"];
            };
        };
        responses: {
            /** @description Result stored and health policy applied */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid internal credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsertEncryptedProfileBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileBinding"];
            };
        };
        responses: {
            /** @description Profile URI encrypted and binding stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid profile URI */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid internal credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint is not granted by the subscription plan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runNextProvisioningJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue state after attempting to process one job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisioningRunResult"];
                };
            };
            /** @description Invalid internal credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInfrastructureSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infrastructure health counters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureSummary"];
                };
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description infrastructure.read permission required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listControlPlaneSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control-plane sources and inventory state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPlaneSourceSummary"][];
                };
            };
        };
    };
    listInfrastructureEndpoints: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sourceCode?: string;
                countryCode?: string;
                protocol?: string;
                healthStatus?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered endpoint inventory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureEndpointPage"];
                };
            };
        };
    };
    listInfrastructureIncidents: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: "OPEN" | "ACKNOWLEDGED" | "RESOLVED";
                severity?: "INFO" | "WARNING" | "CRITICAL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infrastructure incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureIncidentPage"];
                };
            };
        };
    };
    listEndpointGroups: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: "ACTIVE" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Endpoint groups with member and plan counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointGroupPage"];
                };
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description infrastructure.read permission required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createEndpointGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEndpointGroup"];
            };
        };
        responses: {
            /** @description Endpoint group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointGroupDetail"];
                };
            };
            /** @description Invalid endpoint group payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description infrastructure.write permission required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint group code already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEndpointGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Endpoint group detail with member endpoints and attached plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointGroupDetail"];
                };
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEndpointGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEndpointGroup"];
            };
        };
        responses: {
            /** @description Endpoint group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointGroupSummary"];
                };
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description infrastructure.write permission required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceEndpointGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceEndpointGroupMembers"];
            };
        };
        responses: {
            /** @description Endpoint group membership replaced with the given endpoint set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointGroupMembership"];
                };
            };
            /** @description Unknown endpoint id in payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description infrastructure.write permission required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceEndpointGroupPlans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceEndpointGroupPlans"];
            };
        };
        responses: {
            /** @description Plans allowed to use this endpoint group, fully replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointGroupPlanAccess"];
                };
            };
            /** @description Unknown plan id in payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Staff authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description infrastructure.write permission required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Endpoint group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
